"""empty message

Revision ID: 6ddbc1f8c9e2
Revises: 90345472a3b9
Create Date: 2023-09-02 12:19:39.208575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ddbc1f8c9e2'
down_revision = '90345472a3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('bio',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###
