"""empty message

Revision ID: 90345472a3b9
Revises: 09f549634cc7
Create Date: 2023-08-30 20:08:28.082899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90345472a3b9'
down_revision = '09f549634cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
